AWS_REGION: eu-west-1
DB_NAME: serverless-db
DB_USERNAME: master
DB_PASSWORD: password
DB_HOST: serverless-db-stage-aurorardscluster-1h631fha78lhr.cluster-c6xaggiujkbp.eu-west-1.rds.amazonaws.com
DB_PORT: 3306
VPC_ID: vpc-0a6ca43ae47896d20